const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use("/api/auth", require("./routes/auth.routes"));
app.use("/api/students", require("./routes/student.routes"));
app.use("/api/teachers", require("./routes/teacher.routes"));
app.use("/api/attendance", require("./routes/attendance.routes"));
app.use("/api/exams", require("./routes/exam.routes"));
app.use("/api/timetable", require("./routes/timetable.routes"));
app.use("/api/fees", require("./routes/fee.routes"));
app.use("/api/notifications", require("./routes/notification.routes"));
app.use("/api/analytics", require("./routes/analytics.routes"));
app.use("/api/classes", require("./routes/class.routes"));
app.get("/health", (req, res) => { res.json({ status: "OK", message: "SEMS API is running" }); });
app.use((err, req, res, next) => { console.error(err.stack); res.status(500).json({ message: "Error", error: err.message }); });
module.exports = app;